services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./config/clickhouse-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clickhouse.rule=Host(`clickhouse.localhost`)"
      - "traefik.http.services.clickhouse.loadbalancer.server.port=8123"
    depends_on:
      - traefik

volumes:
  clickhouse_data:
    external: true

networks:
  traefik-public:
    external: true

