services:
  auth-service:
    build:
      context: ../../auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - AUTH_PATH=${AUTH_PATH}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_DB_HOST=postgres-auth-db
      - AUTH_DB_PORT=5432
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`${API_HOST}`) && PathPrefix(`${AUTH_PATH}`)"
      - "traefik.http.services.auth.loadbalancer.server.port=${API_PORT}"
      - "traefik.http.middlewares.auth-strip-prefix.stripprefix.prefixes=${AUTH_PATH}"
      - "traefik.http.routers.auth.middlewares=auth-strip-prefix@docker"
    networks:
      - traefik-public
    depends_on:
      - postgres-auth-db
      - rabbitmq-broker
      - traefik

  postgres-auth-db:
    extends:
      file: ./postgres-auth/docker-compose.yml
      service: postgres-auth-db

  rabbitmq-broker:
    extends:
      file: ./rabbitmq/docker-compose.yml
      service: rabbitmq-broker

  traefik:
    extends:
      file: ./traefik/docker-compose.yml
      service: traefik

volumes:
  postgres_auth_data:
  rabbitmq_data:

networks:
  traefik-public:
    external: true