apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres-auth
        image: citusdata/citus:11.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: voxelheim-dev-env
              key: AUTH_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: voxelheim-dev-secret
              key: AUTH_DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voxelheim-dev-secret
              key: AUTH_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
spec:
  selector:
    app: postgres-auth
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-auth
spec:
  entryPoints:
    - postgres-auth
  routes:
  - match: HostSNI(`*`)
    services:
    - name: postgres-auth
      port: 5432

