global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  postgres-game:
    address: ":5432"
  postgres-auth:
    address: ":5433"
  dragonfly:
    address: ":6379"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false