services:
  traefik:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true