services:
  postgres-auth-db:
    image: citusdata/citus:12.1.6
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - ./config/db.conf:/etc/postgresql/postgresql.conf
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres-auth-db.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres-auth-db.entrypoints=postgres"
      - "traefik.tcp.services.postgres-auth-db.loadbalancer.server.port=5432"

volumes:
  postgres_auth_data:

networks:
  traefik-public:
    external: true