services:
  traefik:
    image: traefik:v3.2.2
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true